#!/usr/bin/env python3

from pathlib import Path

import fluidfoam as ff
import numpy as np

PROBLEM_DIR = Path(__file__).parent / "buoyantCavity"
TEMP = "T"


class Boundary:
    FRONT_AND_BACK = "frontAndBack"
    TOP_AND_BOTTOM = "topAndBottom"


front_and_back_0 = ff.readfield(
    str(PROBLEM_DIR),
    time_name="0",
    name=TEMP,
    boundary=Boundary.FRONT_AND_BACK,
)
front_and_back_05 = ff.readfield(
    str(PROBLEM_DIR),
    time_name="0.5",
    name=TEMP,
    boundary=Boundary.FRONT_AND_BACK,
)
front_and_back_1 = ff.readfield(
    str(PROBLEM_DIR),
    time_name="1",
    name=TEMP,
    boundary=Boundary.FRONT_AND_BACK,
)

np.testing.assert_equal(front_and_back_1, front_and_back_05)
